// <auto-generated />
using System;
using CarRentalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalManagement.Migrations
{
    [DbContext(typeof(CarRentalManagementContext))]
    [Migration("20251203063257_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalManagement.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colour");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5471),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5498),
                            Name = "Black",
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5502),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5503),
                            Name = "Blue",
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Make");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5811),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5812),
                            Name = "BMW",
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5814),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5815),
                            Name = "Toyota",
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Model");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5963),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5964),
                            Name = "i4",
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5967),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5968),
                            Name = "X5",
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5969),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5970),
                            Name = "Prius",
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            DateCreated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5972),
                            DateUpdated = new DateTime(2025, 12, 3, 14, 32, 56, 142, DateTimeKind.Local).AddTicks(5972),
                            Name = "C-HR",
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
